### ISSUE TITLE
Check all model documentation for standardization (Trac #646)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasmodels#106]
In particular ensure that sections are in standard order, all equation images are removed and that reference and reviewed by sections are included.

Migrated from http://trac.sasview.org/ticket/646
```json
{
    "status": "closed",
    "changetime": "2019-03-27T17:03:51",
    "_ts": "2019-03-27 17:03:51.723147+00:00",
    "description": "In particular ensure that sections are in standard order, all equation images are removed and that reference and reviewed by sections are included.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-09-05T02:56:55",
    "component": "sasmodels",
    "summary": "Check all model documentation for standardization",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "butler",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/10/01 16:55:23`: 
* **butler** commented:

Not critical for 4.0 - documentation is OK if variable.  Will move this to 4.1 so we can release 4.0 now.


* **butler** changed milestone from "SasView 4.0.0" to "SasView 4.1.0"

**Comment by butlerpd** [comment]
Trac update at `2016/10/06 22:12:39`: **butler** commented:

In changeset adc753dbe4450955415a1427496ad3341a93896e:

```text
#!CommitTicketReference repository="sasmodels" revision="adc753dbe4450955415a1427496ad3341a93896e"
bicelle model documentation standardized, ref to original derivation and
equations added to rst documentation. re SasView/sasview#824 and #106
```

**Comment by butlerpd** [comment]
Trac update at `2016/10/11 12:16:18`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/11/27 01:30:54`: **butler** commented:

In changeset 755ecc2c8863bbe3bdb29424e14f1f9a805f7e6e:

```text
#!CommitTicketReference repository="sasmodels" revision="755ecc2c8863bbe3bdb29424e14f1f9a805f7e6e"
Update documentation to meet standards. addresses #106
```

**Comment by butlerpd** [comment]
Trac update at `2016/11/27 01:30:55`: **butler** commented:

In changeset 5810f00b5c1f61f1386ab0be011468bf48fbf8c0:

```text
#!CommitTicketReference repository="sasmodels" revision="5810f00b5c1f61f1386ab0be011468bf48fbf8c0"
updating documentation to meet standards. Addresses #106
```

**Comment by butlerpd** [comment]
Trac update at `2016/11/27 21:26:00`: **butler** commented:

In changeset 98ce141a6e091b02f8139ab3b235c16dafbce663:

```text
#!CommitTicketReference repository="sasmodels" revision="98ce141a6e091b02f8139ab3b235c16dafbce663"
correct normalization problem in stacked_disk fixes #128. Also heavy
cleanup and correction of equations to match code as well as
standardization of the model documentation addressing #106.
```

**Comment by butlerpd** [comment]
Trac update at `2016/11/28 05:53:15`: **butler** commented:

In changeset 07300ea35d16b40f790fffc4ded20189ec5267a4:

```text
#!CommitTicketReference repository="sasmodels" revision="07300ea35d16b40f790fffc4ded20189ec5267a4"
update, correct and standardize documentation for fractal_core_shell as
well as small tweak to stacked_disk documentation.  Addresses #106
```

**Comment by butlerpd** [comment]
Trac update at `2017/03/13 04:05:41`: **butler** commented:

In changeset 5d23de23656b990e141f01721eb85cd0afaa4dc2:

```text
#!CommitTicketReference repository="sasmodels" revision="5d23de23656b990e141f01721eb85cd0afaa4dc2"
Fold caveats from original IGOR documentation back into sasmodels
version as requested on sasmodels pull request 27 addressing ticket 843.
Also reformated refs and authorship section as per ticket #106
```

**Comment by ajj** [comment]
Trac update at `2017/03/16 20:38:56`: **ajj** changed milestone from "SasView 4.1.0" to "SasView 4.2.0"

**Comment by butlerpd** [comment]
Trac update at `2017/08/27 00:18:52`: **butler** commented:

In changeset d439007cd436f6eef212f3d956711e6f3d29f2fb:

```text
#!CommitTicketReference repository="sasmodels" revision="d439007cd436f6eef212f3d956711e6f3d29f2fb"
Corrected errors in star_polymer documentation identified by MN student
checked carefully against code, benoit paper and Richter paper cited in
ticket. Also took the opportuinty to generally udated and standardize
the documentation as per ongoing process addresses #106. fixes #154
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 16:38:42`: **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by smk78** [comment]
Trac update at `2019/03/27 17:03:16`: **smk78** commented:

In addressing #146, #188, and SasView/sasview#1266 I have been through every single P(q) and S(q) model file and:

* corrected typos where spotted
* changed wording/layout in places (for consistency, standardisation, etc)
* added some additional references
* ensured all files have Authorship & Verification sections (even if some fields are empty!)
* added links to the source code on !GitHub
* checked all models have equations (except where noted in the tickets above)
* removed a legacy png formula

I now consider that the look and content of the model documentation is in pretty good shape and that this ticket can now be closed. Specific issues should now be raised in specific tickets.

**Comment by smk78** [comment]
Trac update at `2019/03/27 17:03:51`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
