### ISSUE TITLE
Write/enhance gpu_computation.rst (Trac #680)

### ISSUE THREAD

**Issue by ajj** [SasView/sasmodels#107]
As per ticket SasView/sasview#809 we need to make sure that the documentation for writing models that will use the GPU includes advice about kernel size, memory usage and some links to OpenCL documentation?

Migrated from http://trac.sasview.org/ticket/680
```json
{
    "status": "closed",
    "changetime": "2016-10-26T15:37:33",
    "_ts": "2016-10-26 15:37:33.985651+00:00",
    "description": "As per ticket #678 we need to make sure that the documentation for writing models that will use the GPU includes advice about kernel size, memory usage and some links to OpenCL documentation?",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-10-04T11:22:16",
    "component": "sasmodels",
    "summary": "Write/enhance gpu_computation.rst",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2016/10/11 16:44:41`: **smk78** changed summary from "Write/enhance model writing documentation" to "Write/enhance gpu_computation.rst"

**Comment by pkienzle** [comment]
Trac update at `2016/10/25 20:12:51`: 
* **pkienzle** changed owner from "" to "pkienzle"
* **pkienzle** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2016/10/26 13:06:04`: 
* **smk78** changed _comment0 from:

> pkienzle says:
> 
> I updated perspectives/fitting/media/plugin.rst including the sections:
> 
>     Embedded C Models
>     Special Functions
>     Problems with C models
> 
> I'm a little worried about providing too much documentation.
> 

to:

> 1477487176850104


* **smk78** commented:

''pkienzle says:''

I updated perspectives/fitting/media/plugin.rst including the sections:

    Embedded C Models
    Special Functions
    Problems with C models

I'm a little worried about providing too much documentation.

**Comment by smk78** [comment]
Trac update at `2016/10/26 13:07:30`: **smk78** commented:

Text has been reviewed by smk78. Minor changes only.

**Comment by smk78** [comment]
Trac update at `2016/10/26 13:07:56`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
