### ISSUE TITLE
Link to documentation on available library routines (Trac #772)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasmodels#121]
We need to make clear to users developing their own c models what library routines are available and the fact that these have usually been optimized for speed, accuracy around 0 and to run on GPU. Probably need to put this in the plugin writer as well as in a link somewhere in the marketplace (linking to the appropriate place within the documentation file posted on the web).

Migrated from http://trac.sasview.org/ticket/772
```json
{
    "status": "closed",
    "changetime": "2016-12-15T08:06:52",
    "_ts": "2016-12-15 08:06:52.386980+00:00",
    "description": "We need to make clear to users developing their own c models what library routines are available and the fact that these have usually been optimized for speed, accuracy around 0 and to run on GPU. Probably need to put this in the plugin writer as well as in a link somewhere in the marketplace (linking to the appropriate place within the documentation file posted on the web).",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-10-11T13:58:34",
    "component": "sasmodels",
    "summary": "Link to documentation on available library routines",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "wojciech",
    "type": "enhancement"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/10/25 21:00:43`: **pkienzle** commented:

The functions are documented in `perspectives/fitting/media/plugin.rst`.

This should be made available from the advanced model editor help menu, or from a HELP button on the advance model editor panel.

Also see #107.

**Comment by smk78** [comment]
Trac update at `2016/10/25 21:00:43`: **smk78** changed _comment0 from:

> The functions are documented in `perspectives/fitting/media/plugin.rst`.
> 
> This should be made available from the advanced model editor help menu, or from a HELP button on the advance model editor panel.

to:

> 1477487745520596

**Comment by smk78** [comment]
Trac update at `2016/10/26 13:08:51`: **smk78** changed summary from "Document available library routines" to "Link to documentation on available library routines"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/11/16 08:47:16`: **wojciech** changed status from "new" to "assigned"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/12/15 08:06:52`: 
* **wojciech** changed resolution from "" to "fixed"
* **wojciech** changed status from "assigned" to "closed"
