### ISSUE TITLE
_handle error at non-opencl platform when data is loaded (Trac #778)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasmodels#124]
When data is loaded first time model computation raise _handle error:
!AttributeError: '!NoneType' object has no attribute '_handle'. 

It is most like triggered by kernell.dll release() fucntion (line 336). I activated this function to make plugin models recompiled. It doesn't seem to cause any trouble apart from anoying message but needs to be fixed. This may be tcc issue only.

Migrated from http://trac.sasview.org/ticket/778
```json
{
    "status": "closed",
    "changetime": "2016-12-20T09:43:52",
    "_ts": "2016-12-20 09:43:52.143233+00:00",
    "description": "When data is loaded first time model computation raise _handle error:\n!AttributeError: '!NoneType' object has no attribute '_handle'. \n\nIt is most like triggered by kernell.dll release() fucntion (line 336). I activated this function to make plugin models recompiled. It doesn't seem to cause any trouble apart from anoying message but needs to be fixed. This may be tcc issue only.",
    "reporter": "wojciech",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-12T00:03:24",
    "component": "sasmodels",
    "summary": "_handle error at non-opencl platform when data is loaded",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/20 08:33:27`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/21 08:59:12`: **wojciech** commented:

In changeset 880e84561dc182c3b191ad7eba368a7725abcc72:

```text
#!CommitTicketReference repository="sasview" revision="880e84561dc182c3b191ad7eba368a7725abcc72"
Adding short time delay upon model loading to prevent double compilation. It is releated to _handle error reported in #124
```

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/21 09:23:43`: **wojciech** commented:

In changeset def512c24c49b6fd47e37a8368e15a18642f2949:

```text
#!CommitTicketReference repository="sasview" revision="def512c24c49b6fd47e37a8368e15a18642f2949"
Fixing double compilation for all Windows (regardless if OpenCL installed tor not). Related to #124
```

**Comment by pkienzle** [comment]
Trac update at `2016/10/27 15:02:54`: **pkienzle** commented:

See also ticket SasView/sasview#798.  If you can avoid evaluating the model twice then it won't try to compile twice and there will be no conflict and no need for an artificial sleep.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/12/20 09:43:52`: 
* **wojciech** changed resolution from "" to "fixed"
* **wojciech** changed status from "assigned" to "closed"
