### ISSUE TITLE
LogicError setting upper Q range limit (Trac #794)

### ISSUE THREAD

**Issue by smk78** [SasView/sasmodels#131]
Win v4.0 release

Whilst trying to reduce the Max Q fit setting on a dataset ranging from 0.007 - 0.25 to 0.007 - 0.07 using the sphere model with polydispersity on I got the following error:

Traceback (most recent call last):
  File "sas\sascalc\data_util\calcthread.pyc", line 268, in _run
!LogicError: clEnqueueReadBuffer failed: invalid value

Setting the Max Q to 0.1 instead of 0.07 did not generate the error.

The logic test generating this is probably fine, but the error is a bit alarming for a user!

Migrated from http://trac.sasview.org/ticket/794
```json
{
    "status": "closed",
    "changetime": "2017-02-07T19:44:56",
    "_ts": "2017-02-07 19:44:56.763825+00:00",
    "description": "Win v4.0 release\n\nWhilst trying to reduce the Max Q fit setting on a dataset ranging from 0.007 - 0.25 to 0.007 - 0.07 using the sphere model with polydispersity on I got the following error:\n\nTraceback (most recent call last):\n  File \"sas\\sascalc\\data_util\\calcthread.pyc\", line 268, in _run\n!LogicError: clEnqueueReadBuffer failed: invalid value\n\nSetting the Max Q to 0.1 instead of 0.07 did not generate the error.\n\nThe logic test generating this is probably fine, but the error is a bit alarming for a user!",
    "reporter": "smk78",
    "cc": "Piotr.Rozyczko@esss.se",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-24T13:32:10",
    "component": "sasmodels",
    "summary": "LogicError setting upper Q range limit",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2016/10/25 17:16:04`: **smk78** changed summary from "LogicError setting Q range with polydispersity on" to "LogicError setting upper Q range limit"

**Comment by smk78** [comment]
Trac update at `2016/10/25 17:18:46`: **smk78** commented:

On further investigation, this seems not to have anything to do with turning polydispersity on.

With the attached example data (some typically noisy, slightly oversubtracted user data):
Load it
Send it to fitting
Select sphere category
Select sphere model
Try and change the upper Q bound for fitting to a number between 0.068 - 0.073

**Comment by smk78** [comment]
Trac update at `2016/10/25 17:19:28`: 
* **smk78** changed attachment from "" to "some_users_data.txt"
* **smk78** commented:

some_users_data.txt

**Comment by smk78** [comment]
Trac update at `2016/10/25 17:22:15`: **smk78** commented:

We have introduced this error in 4.0. The limits work fine in 3.1.2.

**Comment by butlerpd** [comment]
Trac update at `2016/11/08 14:36:32`: 
* **butler** changed owner from "" to "wojciech"
* **butler** changed status from "new" to "assigned"

**Comment by rozyczko** [comment]
Trac update at `2016/11/11 11:55:03`: 
* **piotr** changed cc from "" to "Piotr.Rozyczko@esss.se"
* **piotr** changed component from "SasView" to "sasmodels"

**Comment by pkienzle** [comment]
Trac update at `2017/02/07 19:44:56`: **pkienzle** commented:

This error came about because vectors passed to the GPU are extended to the nearest 16 or 32 value boundary, with some extra space to store the normalization constant.  Some parts of the code were reserving 2 slots while others were requesting 3; only 1 is needed.  To check the fix, sascomp was run with -nq=100 ... -nq=132 on both single and double precision.
