### ISSUE TITLE
rename sas library functions (Trac #804)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#133]
Improve names of sas library functions so that it is easier for the reader to identify what they do.  Suggested names:

    sph_j1c => sas_3j1x_x
    sas_J1c => sas_2J1x_x
    sinc => sas_sinx_x

For consistency:

    Si => sas_Si

Migrated from http://trac.sasview.org/ticket/804
```json
{
    "status": "closed",
    "changetime": "2017-01-17T12:22:47",
    "_ts": "2017-01-17 12:22:47.703157+00:00",
    "description": "Improve names of sas library functions so that it is easier for the reader to identify what they do.  Suggested names:\n\n    sph_j1c => sas_3j1x_x\n    sas_J1c => sas_2J1x_x\n    sinc => sas_sinx_x\n\nFor consistency:\n\n    Si => sas_Si\n\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-11-14T18:34:31",
    "component": "sasmodels",
    "summary": "rename sas library functions",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2016/11/22 09:56:50`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by RichardHeenan** [comment]
Trac update at `2016/12/07 10:20:30`: **richardh** commented:

I will be very happy with the new names, as proposed here, since they have the scalar constants indicated in them, and the "divide by x" part. This makes checking of code and documentation much easier and less prone to errors or misunderstandings.

I suppose that Si(x) is sufficiently well known as sin(x)/x to stay as sas_Si
Richard

**Comment by butlerpd** [comment]
Trac update at `2016/12/20 16:55:44`: 
* **butler** changed component from "SasView" to "sasmodels"
* **butler** changed priority from "minor" to "major"

**Comment by wpotrzebowski** [comment]
Trac update at `2017/01/17 11:49:57`: 
* **wojciech** changed resolution from "" to "fixed"
* **wojciech** changed status from "assigned" to "closed"

**Comment by wpotrzebowski** [comment]
Trac update at `2017/01/17 12:22:47`: **wojciech** commented:

In changeset ca6cbc1cb491a7c62055c86b9919549b87b000bc:

```text
#!CommitTicketReference repository="sasview" revision="ca6cbc1cb491a7c62055c86b9919549b87b000bc"
Updated documentation for lib functions in sasmodels. Refers to ticket 804
```
