### ISSUE TITLE
update docs for oriented shapes with new orientation definition (Trac #891)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#148]
Now that we are treating theta as angle relative to qz and phi as rotation in the qx-qy plane, all the diagrams describing orientation need to be checked to see that they are consistent with this new definition.

Migrated from http://trac.sasview.org/ticket/891
```json
{
    "status": "closed",
    "changetime": "2017-11-28T15:04:52",
    "_ts": "2017-11-28 15:04:52.962877+00:00",
    "description": "Now that we are treating theta as angle relative to qz and phi as rotation in the qx-qy plane, all the diagrams describing orientation need to be checked to see that they are consistent with this new definition.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2017-03-21T13:41:15",
    "component": "sasmodels",
    "summary": "update docs for oriented shapes with new orientation definition",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/03/21 14:45:55`: **butler** commented:

Richard says all symmetric particles are now correct in documentation as well as figures.  Assymeteric of course still needs work as part of #147.

**Comment by pkienzle** [comment]
Trac update at `2017/03/21 15:13:37`: **pkienzle** changed milestone from "SasView 4.1.0" to "SasView 4.2.0"

**Comment by butlerpd** [comment]
Trac update at `2017/03/21 15:16:21`: 
* **butler** changed owner from "" to "pkienzle"
* **butler** changed status from "new" to "assigned"

**Comment by pkienzle** [comment]
Trac update at `2017/11/28 15:04:52`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"
