### ISSUE TITLE
mass_surface_fractal model documentation, unit tests, defaults are wrong (Trac #1105)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasmodels#176]
With thanks to Greg Smith for querying this.

The equations and code in mass_surface_fractal are I think correct, however the documentation, default parameters and unit test examples in sasview are wrong!

The “primary particle” radius should be the smaller one (not the larger one) which is envisaged as having a surface fractal (i.e. smooth or rough surfaces) and then sticking together into a larger cluster radius via a mass fractal packing. (The authors also note that polydispersity in the primary particle size might produce similar effects to the surface fractal at high Q, so results might be ambiguous. Though for their fumed silicas microscopy tends to show that the primary particles are pretty monodisperse.)

The problem seems to have arisen in that the Schmidt review paper referenced in the documentation attempted to reformulate the equations and variable names from the original  Hurd, Schaefer & Martin paper but in doing so managed to get the description wrong, the equations incomplete, and swap the primary and cluster radii around. The sasview documentation alas followed this erroneous description!

Migrated from http://trac.sasview.org/ticket/1105
```json
{
    "status": "closed",
    "changetime": "2018-11-14T00:00:57",
    "_ts": "2018-11-14 00:00:57.580957+00:00",
    "description": "With thanks to Greg Smith for querying this.\n\nThe equations and code in mass_surface_fractal are I think correct, however the documentation, default parameters and unit test examples in sasview are wrong!\n\nThe \u201cprimary particle\u201d radius should be the smaller one (not the larger one) which is envisaged as having a surface fractal (i.e. smooth or rough surfaces) and then sticking together into a larger cluster radius via a mass fractal packing. (The authors also note that polydispersity in the primary particle size might produce similar effects to the surface fractal at high Q, so results might be ambiguous. Though for their fumed silicas microscopy tends to show that the primary particles are pretty monodisperse.)\n\nThe problem seems to have arisen in that the Schmidt review paper referenced in the documentation attempted to reformulate the equations and variable names from the original  Hurd, Schaefer & Martin paper but in doing so managed to get the description wrong, the equations incomplete, and swap the primary and cluster radii around. The sasview documentation alas followed this erroneous description!",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-05-30T14:24:06",
    "component": "sasmodels",
    "summary": "mass_surface_fractal model documentation, unit tests, defaults are wrong",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "richardh",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2018/05/30 14:30:28`: **smk78** commented:

Greg Smith adds:
The Hurd paper was the one I was using for inspiration (in general actually, as we are looking at fumed silica scatters), and I have just cross-referenced it against the !SasView documentation. The equations seem correct in relation to the Hurd paper, it just seems the default parameters that are transposed. (If indeed in the code, rg_cluster = R_g and rg_primary = r_g, as it seems you suggest as well.) The default parameters appear to be HS-5 Cab-O-Sil from Table 1 in Hurd (Phys Rev A), just with the primary and cluster rg the other way around.

**Comment by butlerpd** [comment]
Trac update at `2018/11/14 00:00:57`: **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.0"
