### ISSUE TITLE
beta(Q) approx models to edit (Trac #1120)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasmodels#180]
Need add lists here of high, medium and low priority models to edit.

Note unit tests for P(Q)S(Q) are part of #168 

Migrated from http://trac.sasview.org/ticket/1120
```json
{
    "status": "new",
    "changetime": "2018-10-30T22:42:20",
    "_ts": "2018-10-30 22:42:20.877679+00:00",
    "description": "Need add lists here of high, medium and low priority models to edit.\n\nNote unit tests for P(Q)S(Q) are part of\u00a0#1063\u00a0",
    "reporter": "richardh",
    "cc": "",
    "resolution": "",
    "workpackage": "Beta Approximation Project",
    "time": "2018-07-01T21:35:14",
    "component": "sasmodels",
    "summary": "beta(Q) approx models to edit",
    "priority": "critical",
    "keywords": "",
    "milestone": "sasmodels 1.0",
    "owner": "richardh",
    "type": "enhancement"
}
```

**Comment by pkienzle** [comment]
Trac update at `2018/07/05 20:34:00`: 
* **pkienzle** changed _comment0 from:

> models with easy access to form factor:
> {{{
> adsorbed_layer
> barbell
> capped_cylinder
> core_multi_shell
> core_shell_bicelle
> core_shell_bicelle_elliptical
> core_shell_cylinder
> core_shell_ellipsoid
> core_shell_parallelepipied
> core_shell_sphere
> cylinder  # limiting conditions (long rods, thin disks) don't compute <F>
> ellipsoid
> elliptical_cylinder
> fuzzy_sphere
> hollow_cylinder
> hollow_rectangular_prism
> hollow_rectangular_prism_thin_walls
> multilayer_vesicle
> onion
> parallelepiped
> rectangular_prism
> sphere
> spherical_sld
> triaxial_ellipsoid
> vesicle
> }}}
> models without easy access to form factor
> {{{
> binary_hard_sphere
> core_shell_bicelle_elliptical_belt_rough  # the rough applies to F^2
> flexible_cylinder
> flexible_cylinder_elliptical
> linear_pearls
> mono_gauss_coil
> pearl_necklace
> poly_gauss_coil
> polymer_micelle
> pringle
> raspberry
> stacked_disks
> star_polymer
> }}}
> models with overall structure factor built in:
> {{{
> bcc_paracrystal
> fcc_paracrystal
> fractal
> fractal_core_shell
> lamellar
> lamellar_hg
> lamellar_hg_stack_caille
> lamellar_stack_caille
> lamellar_stack_paracrystal
> mass_fractal
> mass_surface_fractal
> rpa
> sc_paracrystal
> surface_fractal
> }}}
> models which are pure structure factors
> {{{
> hardsphere
> hayter_msa
> squarewell
> stickyhardsphere
> }}}
> other models
> {{{
> be_polyelectrolyte
> broad_peak
> correlation_length
> dab
> gauss_lorentz_gel
> gaussian_peak
> gel_fit
> guinier_porod
> guinier
> line
> lorentz
> peak_lorentz
> polymer_excl_volume
> porod
> power_law
> spinodal
> teubner_strey
> two_lorentzian
> unified_power_Rg
> }}}

to:

> 1534260910209072


* **pkienzle** changed _comment1 from:

> models with easy access to form factor:
> {{{
> barbell
> capped_cylinder
> core_multi_shell
> core_shell_bicelle
> core_shell_bicelle_elliptical
> core_shell_cylinder
> core_shell_ellipsoid
> core_shell_parallelepipied
> core_shell_sphere
> cylinder  # limiting conditions (long rods, thin disks) don't compute <F>
> ellipsoid
> elliptical_cylinder
> fuzzy_sphere
> hollow_cylinder
> hollow_rectangular_prism
> hollow_rectangular_prism_thin_walls
> multilayer_vesicle
> onion
> parallelepiped
> rectangular_prism
> sphere
> spherical_sld
> triaxial_ellipsoid
> vesicle
> }}}
> models without easy access to form factor
> {{{
> binary_hard_sphere
> core_shell_bicelle_elliptical_belt_rough  # the rough applies to F^2
> flexible_cylinder
> flexible_cylinder_elliptical
> linear_pearls
> mono_gauss_coil
> pearl_necklace
> poly_gauss_coil
> polymer_micelle
> pringle
> raspberry
> stacked_disks
> star_polymer
> }}}
> models with overall structure factor built in:
> {{{
> bcc_paracrystal
> fcc_paracrystal
> fractal
> fractal_core_shell
> lamellar
> lamellar_hg
> lamellar_hg_stack_caille
> lamellar_stack_caille
> lamellar_stack_paracrystal
> mass_fractal
> mass_surface_fractal
> rpa
> sc_paracrystal
> surface_fractal
> }}}
> models which are pure structure factors
> {{{
> hardsphere
> hayter_msa
> squarewell
> stickyhardsphere
> }}}
> other models
> {{{
> adsorbed_layer
> be_polyelectrolyte
> broad_peak
> correlation_length
> dab
> gauss_lorentz_gel
> gaussian_peak
> gel_fit
> guinier_porod
> guinier
> line
> lorentz
> peak_lorentz
> polymer_excl_volume
> porod
> power_law
> spinodal
> teubner_strey
> two_lorentzian
> unified_power_Rg
> }}}

to:

> 1534261189323202


* **pkienzle** changed _comment2 from:

> models with easy access to form factor:
> {{{
> barbell
> capped_cylinder
> core_multi_shell
> core_shell_bicelle
> core_shell_bicelle_elliptical
> core_shell_bicelle_elliptical_belt_rough
> core_shell_cylinder
> core_shell_ellipsoid
> core_shell_parallelepipied
> core_shell_sphere
> cylinder  # limiting conditions (long rods, thin disks) don't compute <F>
> ellipsoid
> elliptical_cylinder
> fuzzy_sphere
> hollow_cylinder
> hollow_rectangular_prism
> hollow_rectangular_prism_thin_walls
> multilayer_vesicle
> onion
> parallelepiped
> rectangular_prism
> sphere
> spherical_sld
> triaxial_ellipsoid
> vesicle
> }}}
> models with local structure factor
> {{{
> flexible_cylinder
> flexible_cylinder_elliptical
> linear_pearls
> mono_gauss_coil
> pearl_necklace
> poly_gauss_coil
> polymer_micelle
> pringle
> raspberry
> stacked_disks
> star_polymer
> }}}
> models with long range structure factor:
> {{{
> binary_hard_sphere
> bcc_paracrystal
> fcc_paracrystal
> fractal
> fractal_core_shell
> lamellar
> lamellar_hg
> lamellar_hg_stack_caille
> lamellar_stack_caille
> lamellar_stack_paracrystal
> mass_fractal
> mass_surface_fractal
> rpa
> sc_paracrystal
> surface_fractal
> }}}
> models which are pure structure factors
> {{{
> hardsphere
> hayter_msa
> squarewell
> stickyhardsphere
> }}}
> other models
> {{{
> adsorbed_layer
> be_polyelectrolyte
> broad_peak
> correlation_length
> dab
> gauss_lorentz_gel
> gaussian_peak
> gel_fit
> guinier_porod
> guinier
> line
> lorentz
> peak_lorentz
> polymer_excl_volume
> porod
> power_law
> spinodal
> teubner_strey
> two_lorentzian
> unified_power_Rg
> }}}

to:

> 1534261239985298


* **pkienzle** commented:

models with pure form factor:

```text
barbell
capped_cylinder
core_multi_shell
core_shell_bicelle
core_shell_bicelle_elliptical
core_shell_bicelle_elliptical_belt_rough
core_shell_cylinder
core_shell_ellipsoid
core_shell_parallelepipied
core_shell_sphere
cylinder  # limiting conditions (long rods, thin disks) don't compute <F>
ellipsoid
elliptical_cylinder
fuzzy_sphere
hollow_cylinder
hollow_rectangular_prism
hollow_rectangular_prism_thin_walls
multilayer_vesicle
onion
parallelepiped
rectangular_prism
sphere
spherical_sld
triaxial_ellipsoid
vesicle
```
models with local structure factor

```text
flexible_cylinder
flexible_cylinder_elliptical
linear_pearls
mono_gauss_coil
pearl_necklace
poly_gauss_coil
polymer_micelle
pringle
raspberry
stacked_disks
star_polymer
```
models with long range structure factor:

```text
binary_hard_sphere
bcc_paracrystal
fcc_paracrystal
fractal
fractal_core_shell
lamellar
lamellar_hg
lamellar_hg_stack_caille
lamellar_stack_caille
lamellar_stack_paracrystal
mass_fractal
mass_surface_fractal
rpa
sc_paracrystal
surface_fractal
```
models with pure structure factors

```text
hardsphere
hayter_msa
squarewell
stickyhardsphere
```
other models

```text
adsorbed_layer
be_polyelectrolyte
broad_peak
correlation_length
dab
gauss_lorentz_gel
gaussian_peak
gel_fit
guinier_porod
guinier
line
lorentz
peak_lorentz
polymer_excl_volume
porod
power_law
spinodal
teubner_strey
two_lorentzian
unified_power_Rg
```

**Comment by pkienzle** [comment]
Trac update at `2018/08/14 16:13:25`: **pkienzle** commented:

The pure form factor models have been converted to the new Fq API so they now support beta approximation.

**Comment by pkienzle** [comment]
Trac update at `2018/10/30 22:42:20`: 
* **pkienzle** changed component from "SasView" to "sasmodels"
* **pkienzle** changed milestone from "SasView Next Release +1" to "sasmodels 1.0"

**Comment by pkienzle** [comment]
Closing this ticket.  Opened ticket #204 for the more complicated models.
