### ISSUE TITLE
Create a separate Teixeira Fractal Structure Factor (Trac #1168)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasmodels#185]
All our fractal models are simply one of our form factors multiplied by the Teixeira Structure factor.  We could make many more and add subtleties etc and grow a very long list.  The better option would probably be to pull out the Teixeira fractal SQ as a structure factor.  Eventually we may then want to remove the two/three existing combo fractals.  Moving to 5.0 would be the time to do that part though.

Migrated from http://trac.sasview.org/ticket/1168
```json
{
    "status": "closed",
    "changetime": "2019-02-23T23:27:00",
    "_ts": "2019-02-23 23:27:00.261841+00:00",
    "description": "All our fractal models are simply one of our form factors multiplied by the Teixeira Structure factor.  We could make many more and add subtleties etc and grow a very long list.  The better option would probably be to pull out the Teixeira fractal SQ as a structure factor.  Eventually we may then want to remove the two/three existing combo fractals.  Moving to 5.0 would be the time to do that part though.",
    "reporter": "butler",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SasModels New Model",
    "time": "2018-09-06T11:33:39",
    "component": "sasmodels",
    "summary": "Create a separate Teixeira Fractal Structure Factor",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2019/02/23 23:27:00`: 
* **butler** commented:

This is actually a duplicate of an older ticket #130.  Am going to copy the relevant new thoughts to that ticket and close this one.


* **butler** changed resolution from "" to "duplicate"
* **butler** changed status from "new" to "closed"

**Comment by smk78** [comment]
Also see update to https://github.com/SasView/sasmodels/issues/130
