### ISSUE TITLE
let the user set effective radius in P(Q)*S(Q) (Trac #780)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#261]
`sasmodels.product` defines `P(Q)*S(Q)` using the effective radius from `P(Q)` as the `radius_effective` parameter in `S(Q)`.  This is not always correct, and should be under control of the user.  Similarly for `volfraction` and `VR`.

Instead of hard-coding this relationship, make `ER` and `VR` available as derived parameters from the model.  These parameters will only be computed if their value is requested.  Models could potentially allow other derived parameters.

Use `sasmodels.mixture` to multiply the models.  Make sure that it supports arbitrary model expressions, not just A+B.

May want to allow model constraints to be set in the model value field.  When the radius_effective field is edited, the user will see `=A_ER`, indicating the that the ER() derived parameter from model A should be evaluated.  This will save bouncing to a constraints page to indicate a simple constraint.

Migrated from http://trac.sasview.org/ticket/780
```json
{
    "status": "new",
    "changetime": "2018-09-09T07:54:28",
    "_ts": "2018-09-09 07:54:28.363325+00:00",
    "description": "`sasmodels.product` defines `P(Q)*S(Q)` using the effective radius from `P(Q)` as the `radius_effective` parameter in `S(Q)`.  This is not always correct, and should be under control of the user.  Similarly for `volfraction` and `VR`.\n\nInstead of hard-coding this relationship, make `ER` and `VR` available as derived parameters from the model.  These parameters will only be computed if their value is requested.  Models could potentially allow other derived parameters.\n\nUse `sasmodels.mixture` to multiply the models.  Make sure that it supports arbitrary model expressions, not just A+B.\n\nMay want to allow model constraints to be set in the model value field.  When the radius_effective field is edited, the user will see `=A_ER`, indicating the that the ER() derived parameter from model A should be evaluated.  This will save bouncing to a constraints page to indicate a simple constraint.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "Beta Approximation Project",
    "time": "2016-10-13T05:00:59",
    "component": "SasView",
    "summary": "let the user set effective radius in P(Q)*S(Q)",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by RichardHeenan** [comment]
Closing this ticket, as the original aim was acheived and further issues are addressed ielsewhere.
