### ISSUE TITLE
Refactor sum/product model (Trac #587)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#272]
We should be able to define mixture models using something as simple as:

    from sasmodels.sasview_models import mixture
    Model = mixture('sphere', 'cylinder')

rather than large template that is currently produced by a sum model.  This will allow us to evolve the sasview model interface without breaking custom mixture models store in the .sasview/plugin_models. Similarly for product models.

See #715 for more info.

May also consider making mixture/product models as something generated by the user as needed as part of the fit page rather than having to name every mixture that they are using in their fits.

Ideally this would be done as part of the 4.0.0 release so we do not need to support the existing sasview plugin model definitions indefinitely.

Migrated from http://trac.sasview.org/ticket/587
```json
{
    "status": "new",
    "changetime": "2018-07-04T18:50:52",
    "_ts": "2018-07-04 18:50:52.851215+00:00",
    "description": "We should be able to define mixture models using something as simple as:\n\n    from sasmodels.sasview_models import mixture\n    Model = mixture('sphere', 'cylinder')\n\nrather than large template that is currently produced by a sum model.  This will allow us to evolve the sasview model interface without breaking custom mixture models store in the .sasview/plugin_models. Similarly for product models.\n\nSee #583 for more info.\n\nMay also consider making mixture/product models as something generated by the user as needed as part of the fit page rather than having to name every mixture that they are using in their fits.\n\nIdeally this would be done as part of the 4.0.0 release so we do not need to support the existing sasview plugin model definitions indefinitely.\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "Beta Approximation Project",
    "time": "2016-06-22T18:27:40",
    "component": "SasView",
    "summary": "Refactor sum/product model",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
The sum/mixture models were refactored long ago. Certainly by sasmodels 1.0.6 we now have so closing this as done
