### ISSUE TITLE
dnn should be lattice spacing for paracrystalline models (Trac #1156)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#284]
[Copied from ticket comment:4:ticket:805]

The parameter to the model is labelled as nearest neighbour distance, but I believe it is lattice spacing.

In units of lattice spacing, a, the q positions of the peaks are well determined by:

   q = 2*pi/a * sqrt(h^2 + k^2 + l^2)

where SC allows all integer hkl, BCC requires h+k+l even and FCC require hkl all even or hkl all odd. Also need peak multiplicity to predict the peak height, since ```[100] = [-100] = [010] = [0-10] = [001] = [00-1]```, etc.

I checked peak position and height for dnn=20 and d_factor=0.06 for sc, bcc and fcc to verify the calculation.

We should rename dnn to length_a as in the parallelepiped model, and rename d_factor to lattice_distortion. Lattice distortion is actually proportional, Delta a / a, but distortion_proportion is too much of a mouthful.

Migrated from http://trac.sasview.org/ticket/1156
```json
{
    "status": "assigned",
    "changetime": "2018-11-28T01:44:26",
    "_ts": "2018-11-28 01:44:26.486641+00:00",
    "description": "[Copied from ticket comment:4:ticket:805]\n\nThe parameter to the model is labelled as nearest neighbour distance, but I believe it is lattice spacing.\n\nIn units of lattice spacing, a, the q positions of the peaks are well determined by:\n\n   q = 2*pi/a * sqrt(h^2 + k^2 + l^2)\n\nwhere SC allows all integer hkl, BCC requires h+k+l even and FCC require hkl all even or hkl all odd. Also need peak multiplicity to predict the peak height, since {{{[100] = [-100] = [010] = [0-10] = [001] = [00-1]}}}, etc.\n\nI checked peak position and height for dnn=20 and d_factor=0.06 for sc, bcc and fcc to verify the calculation.\n\nWe should rename dnn to length_a as in the parallelepiped model, and rename d_factor to lattice_distortion. Lattice distortion is actually proportional, Delta a / a, but distortion_proportion is too much of a mouthful.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-08-14T15:05:56",
    "component": "SasView",
    "summary": "dnn should be lattice spacing for paracrystalline models",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Some recent discussions with Andrew Whitten of ANSTO who was trying to use this model has managed to finally spur the full review of this issue as well as issue #155 that has been on the back burner for 3 years.  The good news is I think we have now resolved all the issues and the bottom line is that there are some documentation errors and one error in the code itself.

The source of much confusion is the confusing nomenclature used in the 1987 paper used to code this model. There the authors define a set of 3 a_k vectors which are nearest neighbor vectors and a set of 3 orthogonal b_k vectors which are the primary cubic lattice vectors. The unfortunate nomenclature comes from the fact that they use scalar a_k to represent the magnitude of the a_k vector while they then state that the magnitude of the b_k vectors are all equal (true) and that magnitude is called a.

The original programmers and many of us who have tried to review this over the years have made the mistake of assuming that a_k and a were one and the same which is only true for the SC. Both a_k (i.e. d_nn) **and** a (lattice parameter) are used in different places in the equations copied from the paper.  Thus it would be **incorrect** to call d_nn the scale parameter. There is in fact only one place in the code where the lattice parameter should replace d_nn.

A careful read of the code and the papers indicate that everything else seems to be coded correctly including both errors identified in the 1990 paper. Which brings us to the first error in the documentation: Z1,Z2,Z3 are taken from the 1987 paper BUT rewritten based on the 1990 correction (which is a separate correction from the correction of eq 1 in the 1990 paper).  The second error is that the BCC equation for V_lattice is incorrect (it is actually just a copy of the FCC version). Thirdly, scale is **NOT** the volume fraction of spheres but the volume fraction of crystal in the system. Finally, V_lattice, which is a poor choice of nomenclature and should be changed, represents the volume fraction of spheres within the crystal. Thus scale * V_lattice is the total volume fraction of spheres.  Unfortunately V_lattice is computed and used internally to the code only and not returned. Thus the user has no access to the volume fraction of spheres without a manual calculation.

## SUMMARY
### changes needed
* Calculate the lattice parameter (let’s call it b) from `dnn` in the `xxx_zq(qa,qb,qc,dnn, d_factor)` function.
* Replace dnn with the above in the cos terms (and only the cos terms) of the same function.
* Update the documentation as per above.
### options for volume fraction
* Leave everything as is and make the user do manual computation if they want the vol fraction of spheres.
* Remove the V_lattice calculation altogether from the code (and documentation?). In this case scale becomes the total sphere volume fraction but the user will have to do manual calculations if they want to extract the vol fraction of spheres in the crystal and the vol fraction of crystal in the system.
* Add this to our increasing list of place where it would be nice to have the model return computed values.

**Comment by smk78** [comment]
In closing the above, @RichardHeenan notes in https://github.com/SasView/sasmodels/issues/155#issuecomment-1060894357:

>Would strongly suggest that the discussion in https://github.com/SasView/sasmodels/issues/284 is included as a footnote to the model documentation or in the code itself

**Comment by pkienzle** [comment]
I've extended realspace.py to simulate sc/fcc/bcc lattices. See #507
