### ISSUE TITLE
Correlation length model documentation is wrong

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasmodels#367]
In the documentation for the correlation length model, the Lorentzian exponent appears to be wrong.

In 
```math
1/( 1 + (q *  xi)^m)
```
*m* should be dimensionless. It should not be

```math
  Å^{-2}
```

**Comment by smk78** [comment]
Corrected units of lorentz_exp from Å^{-2} to None

**Comment by smk78** [comment]
I also checked all other models with exponents. There were no other issues with the dimensions of exponents.
