### ISSUE TITLE
reparameterize has a bug ( at least in v5)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasmodels#381]
though the new reparameterize has been pulled into sasmodels, it still has a bug,
see 

https://github.com/SasView/sasmodels/pull/211#issuecomment-598159835

Parameters not included in the reparameterize  do not appear in the gui

**Comment by RichardHeenan** [comment]
So I created a branch, with a test model and some debug print out when the model is compiled. It all seems to work perfectly, except the GUI does not display the full parameter table.
I could spend many hours trying to investigate further, it may be an issue with the way the list of parameters are being stored or passed about.  Would be good if Piotr could take a look please, would be simplest for me to demo the branch on Zoom.

**Comment by rozyczko** [comment]
Or you can just attach/send the model for which you see this behaviour.

**Comment by RichardHeenan** [comment]
There’s some debug print in the branch that provides some info.

core_shell_ellipsoid_reparam3

Is the model.

**Comment by rozyczko** [comment]
fixed in ESS_GUI_381_reparameterize

**Comment by rozyczko** [comment]
Added pull request as well
