### ISSUE TITLE
fitting_sq.rst uses F F* but polydispersity.rst uses F* F

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#387]
Following [1], sasmodels/guide/fitting_sq.rst uses F F* in the theory section, whereas sasmodels/guide/pd/polydisperty.rst uses F* F.  These should be consistent.

We may want to incorporate the detailed derivation of the relationship between the scattering of individual particles and the volume fraction of scatterers given in https://github.com/SasView/sasmodels/issues/205#issuecomment-603207732 in the PD page since it explains what we are using in the code.

[1] Kotlarchyk, M., Chen, S.-H., 1983. Analysis of small angle neutron scattering spectra from polydisperse interacting colloids. The Journal of Chemical Physics 79, 2461–2469. https://doi.org/10.1063/1.446055

**Comment by smk78** [comment]
Addressed by PR above.
