### ISSUE TITLE
link polydispersity, orientation, and structure factor docs

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#397]
The theory section of the of structure factor documentation covers polydispersity and orientation. Restructure and cross-link the documentation so that it is consistent and not repeated.

* http://www.sasview.org/docs/user/qtgui/Perspectives/Fitting/fitting_sq.html#theory
* http://www.sasview.org/docs/user/qtgui/Perspectives/Fitting/pd/polydispersity.html
* http://www.sasview.org/docs/user/qtgui/Perspectives/Fitting/orientation/orientation.html

**Comment by pkienzle** [comment]
Also, the pd docs should use `<V>` rather than `V` since it is the average volume.

**Comment by pkienzle** [comment]
see also #387

**Comment by smk78** [comment]
Addressed by PR above.
