### ISSUE TITLE
Create model for helical ribbons

### ISSUE THREAD

**Issue by smk78** [SasView/sasmodels#417]
User JianL has asked if we could code the model for a helical ribbon described in Hamley, 'Form Factor of Helical Ribbons', Macromolecules, 2008, 41, 8948-8950. (https://dx.doi.org/10.1021/ma8014917)

**Comment by pkienzle** [comment]
`realspace.py` has code to sample from a helix. This can be used for a Monte Carlo check against the analytical model.

**Comment by butlerpd** [comment]
Interestingly Hamley was presumably the person asking for the pringle-schmidt helix.  Given conversation in issue #135 about said Pringle-Schmidt model, and the fact that this modle is just a special case of that model. Suggest we shelve this for now. Once Pringle-Shmidt is finalized and tested we can revisit and presumably close this as "duplicate?"

**Comment by lucas-wilkins** [comment]
This exists in the marketplace (@timsnow did it)

**Comment by smk78** [comment]
The P-S is two helical tapes wrapped around each other. If I only wanted to fita single helical tape how would I set the parameters of the P-S helix model to accommodate that? If this is possible then the doc string for the P-S helix should be updated to explain. If it is not possible, then there is still a requirement to implement a suitable (single) helical tape model. So I'm re-opening this issue until these questions are answered.

**Comment by lucas-wilkins** [comment]
> If I only wanted to fita single helical tape how would I set the parameters of the P-S helix model to accommodate that?

Make the gap between the two helices zero

**Comment by smk78** [comment]
And the angle too?

**Comment by lucas-wilkins** [comment]
![image](https://user-images.githubusercontent.com/9784906/201103628-a88d043d-60ee-4128-989a-5c6e7dcf7ded.png)

Set $\varphi = \omega$

**Comment by butlerpd** [comment]
As I recall there was some work on that by the pozzo group at the university of washington.  The whole question of using this model for a single helix vs writing a different model. Do you know anything about that @caitwolf?  I cannot remember the outcome and if there was a reason one could not use this model for a single helix?

**Comment by lucas-wilkins** [comment]
You can absolutely use the same model for a single helix, in fact, one of the references is exactly that case.

**Comment by smk78** [comment]
Ok, then the issue becomes one of documenting this functionality, so I've just opened an issue against the Marketplace for that and will close this issue. Thanks to all for the clarifications.
