### ISSUE TITLE
opencl tests not running on windows

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#425]
Checking the github test action [output](https://github.com/SasView/sasmodels/actions?query=workflow%3ATest+branch%3Amaster), it appears that opencl is not being tested on windows, but it is on ubuntu and mac.

Cuda is not being tested anywhere.

**Comment by andyfaff** [comment]
pyopencl on windows is annoying in this respect, it's not easily available from pip. I tried along the lines of:

```
python -m pip install pytools mako cffi
choco install opencl-intel-cpu-runtime
python -m pip install --only-binary=pyopencl --find-links http://www.silx.org/pub/wheelhouse/ --trusted-host www.silx.org pyopencl
```

but I didn't go further with it. It's probably easier to adjust the windows entries to use conda+conda-forge as pyopencl has a package built for it.

**Comment by pkienzle** [comment]
This appears to be fixed. At least it is saying that opencl is being tested. Closing.
