### ISSUE TITLE
Create model for superparamagnetic relaxing particles

### ISSUE THREAD

**Issue by dehoni** [SasView/sasmodels#429]
A model is missing that describes the SANS of individual (dilute), superparamagnetic particles. This is the "standard tool" to describe magnetic nanoparticle systems. The alignment of the particle moments along the magnetic field is disturbed by thermal fluctuations like Brownian motion of freely rotating particles in a liquid. The magnetic SLD is hence weighted for each magnetisation component with the corresponding average of a Boltzmann orientation distribution [see e.g. A. Wiedenmann, Physica B 356, 246 (2005)]. 
Requirements:
The model should allow not only single homogeneous core, but core-shell systems, and potentially also nanoparticles in a (magnetic) matrix to cover a broad range of use cases possible. Measurements are most often performed with polarised neutrons either with full PA or at least incoming polarisation. It is mandatory to produce differences of scattering cross sections to obtain the nuclear-magnetic interference term. Most often the magnetic field is oriented in the detector plane. Nice to have would be (in a next step) the possibility to freely orient the field axis.

**Comment by dehoni** [comment]
The model seems to do what it should if compiled in SASview. However there are some issues I couldn't solve by myself:
1) most importantly using it as a plugin model fails. This needs desperately a look before it can be shipped for test and verification by the magnetism community. I have dropped the files in the .sasview/plugin_models folder. The model is found by Sasview but produces an error message:

ERROR : sas.qtgui.Perspectives.Fitting.FittingWidget (FittingWidget.py:2371) :: Can't find the model No module named 'sasmodels.models.magnetic_langevin_core_shell'
ERROR : sas.qtgui.Perspectives.Fitting.FittingWidget (FittingWidget.py:174) :: Traceback (most recent call last):
  File "site-packages\sasview-5.0.3-py3.6.egg\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1193, in onSelectModel
  File "site-packages\sasview-5.0.3-py3.6.egg\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1334, in respondToModelStructure
  File "site-packages\sasview-5.0.3-py3.6.egg\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2319, in SASModelToQModel
  File "site-packages\sasview-5.0.3-py3.6.egg\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 3347, in addExtraShells
  File "site-packages\sasview-5.0.3-py3.6.egg\sas\qtgui\Perspectives\Fitting\FittingUtilities.py", line 55, in getMultiplicity
  File "site-packages\sasview-5.0.3-py3.6.egg\sas\qtgui\Perspectives\Fitting\FittingUtilities.py", line 48, in getIterParams
AttributeError: 'NoneType' object has no attribute 'iq_parameters'

2) "Show SLD profile" does not work. That is puzzling as it is not changed and identical to core_multi_shell. I could not figure out where it breaks.

3) Feature request: It would be nice to see together with the nuclear SLD also the magnitude of the magnetic SLD in the same graph.

**Comment by RichardHeenan** [comment]
Suggest you get the new model working for now in the normal ..../sasmodel/models directory, you can have collaborators drop a new model there without having to use the plugin directory, in either developer environment or with a sasview release.
I just tried a sum model of core_multi_shell plus sphere, that also fails with ERROR: SLD profile calculation failed  on trying to plot the sld profile. The "multiplicity models" - the ones with drop down choice of number of layers etc, are special cases, looks like thee is yet another issue with them here.

**Comment by pkienzle** [comment]
1. Works for me on mac from ESS_GUI branch head.

2. The profile function requires the complete parameter list in the order that they appear. It would be useful if it showed the error message and/or the traceback if only in sasview.log rather than "Error: SLD profile calculation failed."

3. This is a bit challenging since it needs to support existing models as well as new. On the sasmodels side, adding magnetic_profile to each model which accepts magnetism parameters associated with the SLDs and adding getProfileMagnetic to sasmodels.sasview_model.SasviewModel is probably the most expedient, though it is a bit ugly. Then update sasview to call getProfileMagnetic if magnetism is turned on for the dataset.

**Comment by dehoni** [comment]
Model added to Sasview Marketplace.

**Comment by dehoni** [comment]
Here is then also the most general description for an arbitrary orientation of the magnetic field. Now it should have the full functionality like found in SASfit. Might be useful to describe AC oscillating and rotating fields like in the TISANE papers by Wiedenmann.

**Comment by dehoni** [comment]
Attached are the tested models. They consistently give the correctly scaled results in 1D and 2D against the reference scattering cross section of a simple sphere.
[Langevinmodels.zip](https://github.com/SasView/sasmodels/files/5934953/Langevinmodels.zip)
