### ISSUE TITLE
Default plugin path in core.py does not exist

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasmodels#433]
user @beikerta alludes to this issue in the closed PR #428. The core problem is what to do when sasmodels cannot find the path to the plugin directory. 

@pkienzle commented in PR#428 that SasView is storing plugin models in `~/.sasview/plugin_models`, as defined by `sas.sascalc.fit.models.find_plugins_dir()`. Nominally, sasmodels does not know that sasview exists so it should not be defaulting its paths to the `~/.sasview` directory. Instead, sasview should be setting SAS_MODELPATH to the appropriate directory on startup. This should be done along with the other sasmodels settings in `sas.qtgui.MainWindow.run_sasview` using something like:
```python
    os.environ["SAS_MODELPATH"] = models.find_plugins_dir()
```
Thinking ahead to batch fitting from script these setting should work even if the GUI is not running so they should be moved outside of sas.qtgui.MainWindow, but that is a separate issue.

while @butlerpd then noted that:
The issue reported however deals with the case when no SAS_MODELPATH env variable is found.  Defaulting to a random non-existent path does not seem like a reasonable answer.

This should probably be replaced with an error capture that is logged?

**Comment by pkienzle** [comment]
It is not an error to have no plugin models, so a non-existent plugin directory should not raise an error. We wouldn't want to force the creation of an empty directory or force the user to set an environment variable when using sasmodels as a library. 

Sasmodels does need other directories such as the cache directory for compiled models, so it needs to know something about how the operating system orders configuration files. Perhaps we should use the [appdirs package](https://pypi.org/project/appdirs/)? It is a dependency for pyopencl so we are already including it.

**Comment by butlerpd** [comment]
The problem I thought was that without defining a path to plugins in en ENV variable, if the user saves a plugin model it `gets lost` because it is not saved where sasmodels can find it?  Quietly ignoring what you asked sasmodels to do seems wrong as would be putting the model in a random place the user (and sasmodels) cannot find. How is this not an error? or am I not understanding the user's problem?

**Comment by pkienzle** [comment]
There is no plugin save feature in sasmodels. That's something from the GUI.

The plugin models from sasview will not be available if you do not go through the sasview config to set the appropriate variables. This means that using sasmodels directly from a script may fail if you run that script outside of sasview and have not set `SAS_MODELPATH=~/.sasview/plugin_models` in the environment.

Within sasview it is possible that there is a timing issue, where sasmodels loads the config variable before sasview has had a chance to set it and therefore the plugins are not available to some models. It doesn't sound like that was the problem.

I'm resetting this discussion as issue #519
