### ISSUE TITLE
Create a library for polarisation and magnetic scattering vector calculations

### ISSUE THREAD

**Issue by dehoni** [SasView/sasmodels#450]
All magnetic models share functions like set_weights, set_scatvec, mag_sld. Refactor the code and make it available in a library file.

**Comment by dehoni** [comment]
Verify that θ, φ use the same orientation system as the particle axis, both for applied field and for orientation of the magnetism within the particle.

**Comment by dehoni** [comment]
[magnetic_functions.c.txt](https://github.com/SasView/sasmodels/files/7692594/magnetic_functions.c.txt)
The file magnetic_function.c is shipped now with all magnetic models on the Sasview Marketplace. The files contains the shared functions for polarised/magnetic scattering.

**Comment by butlerpd** [comment]
@dehoni -- just wondering if this has also been committed to `sasmodels/models/lib`?  If not should it be?

**Comment by dehoni** [comment]
Not yet, but there are also no magnetic models requesting it....
