### ISSUE TITLE
rename parameter up_angle to up_theta for consistency and check conversion from old models

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#471]
Orientation angles are θ, φ, ψ most everywhere but magnetic orientation uses `up_angle` and `up_phi` for historical reasons. Rename `up_angle` to `up_theta` and make sure that older models get converted.

Verify that θ, φ use the same orientation system as the particle axis, both for applied field and for orientation of the magnetism within the particle.

Also, make sure that models saved without `up_phi` are loaded correctly in versions that support arbitrary applied field.

**Comment by dehoni** [comment]
In realspace.py, the rotation matrixes and the definition of [orientation coordinates](https://github.com/SasView/sasmodels/blob/462a07ed6413ea731e6a4f9f0a5edb2c42dcda00/explore/realspace.py#L59) `pol2rec` are consistent with the coordinates for the [polarisation vector](https://github.com/SasView/sasmodels/blob/462a07ed6413ea731e6a4f9f0a5edb2c42dcda00/explore/realspace.py#L604) `p_hat` in the function `magnetic_sld` .
I would need to guess the origin of the expressions for [view and jitter matrices](https://github.com/SasView/sasmodels/blob/462a07ed6413ea731e6a4f9f0a5edb2c42dcda00/sasmodels/kernel_iq.c#L226) in `kernel_iq.c`, such that I can not state if they are in line. Similarly, the dedicated magnetic models in the model market place need an extra look, while doing the refactoring mentioned in [ticket #450](https://github.com/SasView/sasmodels/issues/450).

**Comment by pkienzle** [comment]
Related: sasview generic scattering calculator https://github.com/SasView/sasview/pull/1971
