### ISSUE TITLE
Use up_theta instead of up_angle as model parameter names for consistency

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#473]
Orientation angles are θ, φ, ψ most everywhere but magnetic orientation uses `up_angle` and `up_phi` for historical reasons. Rename `up_angle` to `up_theta` and make sure that older models get converted.

Verify that θ, φ use the same orientation system as the particle axis, both for applied field and for orientation of the magnetism within the particle.

Also, make sure that models saved without `up_phi` are loaded correctly in versions that support arbitrary applied field.

**Comment by dehoni** [comment]
The ticket looks like a doublicate of [ticket 471](https://github.com/SasView/sasmodels/issues/471) .
