### ISSUE TITLE
Show SLD Profile not working in the unified_power_rg model

### ISSUE THREAD

**Issue by smk78** [SasView/sasmodels#475]
Transferred from https://github.com/SasView/sasview/issues/1897

Using Release 5.0.4, clicking the Show SLD Profile button in the unified_power_rg model returns
```
ERROR: SLD profile calculation failed.
```

It works in the onion model...

@rozyczko comments:
`model_info.profile` attribute for this model is `None`, whereas it should be a method to calculate the profile.
This likely is a Sasmodels issue.

**Comment by pkienzle** [comment]
Unified power Rg is not shape-based and doesn't have any SLD profile associated with it.
