### ISSUE TITLE
Equation one in Cylinder model documentation is incorrect.

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasmodels#495]
The P(Q) equation for an oriented cylinder has a sin(alpha) appended at the end. I believe that is incorrect. Only when integrating over all angles (for isotropic case) would one add sin(alpha) dalpha for polar coordinate integration?

**Comment by RichardHeenan** [comment]
I agree !  (Should have seen that  when I last revised the docs.)
The sin(alpha) is for the number of cylinders at that orientation if you think about them pointing uniformly in all directions towards  the surface of a sphere.
Richard
