### ISSUE TITLE
core_multi_shell contextual help indicates that there is max 4 shells

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasmodels#496]
Reported by the user

The core_multi_shell contextual help (so as documentation) indicates that there is max 4 shells

"This model provides the scattering from a spherical core with 1 to 4 concentric shell structures. The SLDs of the core and each shell are individually specified."

but in fact the model accepts 10 shells (at least that seems to work) so the contextual and online helps should be udpated accordingly.

**Comment by butlerpd** [comment]
This was in sasview so did not get closed when it was fixed despite the "fixes" keyword in the sasmodels PR.  This has now been moved to sasmodels and am manually closing it.
