### ISSUE TITLE
Fix confusing slit nomenclature

### ISSUE THREAD

**Issue by pbeaucage** [SasView/sasmodels#528]
In sasview/sasview#1753, we discuss that sasview adopted non-standard (or maybe better pre-standard, or neutron-specific) nomenclature for which axis in slit smearing is the short one and which is the long one.

canSAS defines the slit *width* as the narrow axis, and the slit *length* as the long axis.  We currently call width the narrow axis but call the long axis height, which is correct in the horizontal-scattering USANS geometry but incorrect in a vertical scattering geometry. 
 Length is direction-agnostic and thus preferred, I think.  It would be good to revise our resolution calculator to use this nomenclature as well to avoid confusion.

**Comment by butlerpd** [comment]
closing ticket after merging changes
