### ISSUE TITLE
Changes in #563 break SasView main

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasmodels#573]
The changes in #563 have caused some issues with DirectModel as it used in SasView (and probably peoples scripts).

The text of #563 says its only an error that will occur outside of SasView and just requires different parameter names, but SasView is affected. Whilst changing the names does remove the error, it results in calculations that are incorrect (in parallelepiped at least, ```a``` -> ```length_a``` etc).

**Comment by pkienzle** [comment]
Orientation viewer in sasview seems to function even with the check enabled.

Can we close this ticket? Or are there other cases where things are breaking?
